name: fdatabase_web
description: A implementation of fdatabase for web
version: 0.0.1+2
homepage: https://github.com/tihrasguinho/fdatabase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fdatabase_base: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
